apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ecommerce.local
    http:
      paths:
      {{- range .Values.services }}
      - path: /{{ if ne .name "home" }}{{ .name }}{{ end }} 
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-svc
            port:
              number: 80
      {{- end }}